stages:
  data_ingestion:
    cmd: python data_import.py
    params:
    - config.yml
    outs:
    - data/raw
  data_preprocessing:
    cmd: python preprocessing.py
    deps:
    - data/raw
    - data_import.py
    outs:
    - data/interim
  feature_engineering:
    cmd: uv run feature_engineering.py
    deps:
    - data/interim
    - src/feature_engineering.py
    params:
    - feature_engineering.max_features
    outs:
    - data/processed
  model_building:
    cmd: python src/model_building.py
    deps:
    - data/processed
    - src/model_building.py
    params:
    - model_building.n_estimators
    - model_building.random_state
    outs:
    - models/model.pkl
  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
    - models/rfc.pkl
    - src/model_evaluation.py
    metrics:
    - reports/metrics.json