stages:
  data_importing:
    cmd: uv run data_import.py
    deps:
    - data_import.py
    - config.yaml
    outs:
    - data/raw/
  preprocessing:
    cmd: uv run preprocessing.py
    deps:
    - data_import.py
    - data/raw/
    outs:
    - data/processed_data/
  feature_engineering:
    cmd: uv run feature_engineering.py
    deps:
    - data/processed_data/
    outs:
    - data/tfidf_processed/
  model_building:
    cmd: uv run model_building.py
    deps:
    - data/tfidf_processed/
    - params.yaml
    outs:
    - data/models/
  model_evaluation:
    cmd: uv run model_evaluation.py
    deps:
    - data/models/
    - data/tfidf_processed/
    outs:
    - data/metrics/